layout_spectrum: 0.6550765885040164
typography_spectrum: 0.04189181583933532
color:
  brandColors:
    - '#468966'
    - '#FFF0A5'
    - '#FFB03B'
    - '#B64926'
    - '#8E2800'
  brandStrength: 0.3735589296557009
  lightness: 0.12551047559827566
  saturation: 0.9316069076303393
  rhythmicContrast: 0.6896484410390258
name: Brooks Moorhead
favicon: null
title: B. Moorhead
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
