name: Brooks Moorhead
favicon: null
layout_spectrum: 0.046548869693651795
typography_spectrum: 0.6083362950012088
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b2d2c'
    - '#824526'
    - '#e3b788'
    - '#b2c7d8'
    - '#af9554'
  brandStrength: 0.875
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
